# Build the Astro site, then serve the static output with nginx.
#
# Coolify: New Resource -> Application -> this repository, Build Pack "Dockerfile",
# exposed port 80. Set the build variables in Coolify:
#
#   PUBLIC_SITE_URL   https://jcwh.eptsolution.com   canonical URLs + sitemap
#   PUBLIC_PREVIEW    1                              noindex + robots Disallow: /
#
# See docs/WORKFLOW.md ("Deploying") for the deployment runbook.

FROM node:24-alpine AS build
WORKDIR /app
RUN corepack enable

# Manifests first, so dependency layers are reused when only content changes.
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/site/package.json apps/site/
COPY tools/scraper/package.json tools/scraper/
RUN pnpm install --frozen-lockfile

COPY . .
ARG PUBLIC_SITE_URL
ARG PUBLIC_PREVIEW
RUN pnpm build

FROM nginx:1.27-alpine AS serve
# Redirects for the old site's URLs, generated by the scraper.
COPY deploy/nginx-redirects.conf /etc/nginx/redirects.conf
COPY deploy/nginx-site.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/apps/site/dist /usr/share/nginx/html
EXPOSE 80
